CREATE TABLE IF NOT EXISTS TEAM (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR (50) NOT NULL,
    senha VARCHAR (8) NOT NULL,
    nome VARCHAR(50) NOT NULL,
    dataFundacao DATE NOT NULL,
    patrimonio DOUBLE NOT NULL,
    ID_ATLETA INT NOT NULL,
    ID_JOGO INT NOT NULL,
    ID_FINANCEIRO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ATLETA (
        nome VARCHAR(100) NOT NULL,
        cpf VARCHAR(15) NOT NULL PRIMARY KEY,
        dataNasc DATE NOT NULL,
        telefone VARCHAR(16) NOT NULL,
        email VARCHAR(100),
        endereco VARCHAR(200) NOT NULL,
        salario DOUBLE NOT NULL
); 

CREATE TABLE IF NOT EXISTS JOGO (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dataHoraPartida VARCHAR(50) NOT NULL,
    localJogo  VARCHAR(100) NOT NULL, 
    adversario VARCHAR(100) NOT NULL, 
    competicao VARCHAR(100) NOT NULL,
    lucroPartida double,
    status BOOLEAN NOT NULL,
    stCouF BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS PATROCINIO(
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    valor DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS DESPESA(
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    valor DOUBLE NOT NULL
); 

CREATE TABLE IF NOT EXISTS FINANCEIRO(
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dataBalanco DATE NOT NULL,
    patrocinios DOUBLE NOT NULL,
    despesas DOUBLE NOT NULL,
    lucroPartidas DOUBLE NOT NULL,
    salarios DOUBLE NOT NULL,
    total DOUBLE NOT NULL,
    ID_PATROCINIO INT NOT NULL,
    ID_DESPESA INT NOT NULL
);

ALTER TABLE FINANCEIRO ADD CONSTRAINT IF NOT EXISTS FK_FINANCEIRO_PATROCINIO FOREIGN KEY(ID_PATROCINIO) REFERENCES PATROCINIO(ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE FINANCEIRO ADD CONSTRAINT IF NOT EXISTS FK_FINANCEIRO_DESPESA FOREIGN KEY(ID_DESPESA) REFERENCES DESPESA(ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TEAM ADD CONSTRAINT IF NOT EXISTS FK_TEAM_ATLETA FOREIGN KEY(ID_ATLETA) REFERENCES ATLETA (CPF) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TEAM ADD CONSTRAINT IF NOT EXISTS FK_TEAM_JOGO FOREIGN KEY(ID_JOGO) REFERENCES JOGO (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TEAM ADD CONSTRAINT IF NOT EXISTS FK_TEAM_FINANCEIRO FOREIGN KEY(ID_FINANCEIRO) REFERENCES FINANCEIRO (ID) ON DELETE CASCADE ON UPDATE CASCADE;
